//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доходы_и_расходы
    {
        public int ID_периода { get; set; }
        public bool Положительный { get; set; }
        public decimal Итоговая_сумма { get; set; }
        public decimal Прибыль_от_продаж { get; set; }
        public decimal Затраты_на_комбикорм { get; set; }
        public decimal Затраты_на_электроэнергию { get; set; }
        public decimal Затраты_на_з_п_сотрудников { get; set; }
        public decimal Затраты_на_другое { get; set; }
        public System.DateTime Дата_учёта { get; set; }
    }
}
