//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int ID_заказа { get; set; }
        public bool Собственный { get; set; }
        public Nullable<int> ID_продукции { get; set; }
        public string Наименование_товара { get; set; }
        public Nullable<int> ID_объекта { get; set; }
        public int Количество { get; set; }
        public double Итоговая_цена { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public string Наименование_Юридического_Лица { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Объекты Объекты { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
