//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int ID_продукции { get; set; }
        public string Тип_продукции { get; set; }
        public Nullable<int> Категория { get; set; }
        public Nullable<int> Сорт { get; set; }
        public string Состав { get; set; }
        public int Количество { get; set; }
        public int ID_объекта { get; set; }
        public Nullable<decimal> Цена_за_единицу_товара { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual Склады Склады { get; set; }
    }
}
