//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Цеха_производства = new HashSet<Цеха_производства>();
        }
    
        public int ID_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public bool Пол { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public Nullable<int> ID_объекта { get; set; }
        public string Должность { get; set; }
        public System.DateTime Дата_вступления_в_должность { get; set; }
        public decimal Зарплата { get; set; }
        public string e_mail { get; set; }
        public string Номер_телефона { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Цеха_производства> Цеха_производства { get; set; }
    }
}
