//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Цеха_производства
    {
        public int ID_объекта { get; set; }
        public int Кол_во_сотрудников { get; set; }
        public Nullable<int> ID_начальника_цеха { get; set; }
        public int Общий_объем_инкубаторов { get; set; }
        public int Объем_продукции_в_сутки { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
